/********************************************************************
* LinkDef_out.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LinkDef_out.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLinkDef_out();
extern void G__cpp_setup_inheritanceLinkDef_out();
extern void G__cpp_setup_typetableLinkDef_out();
extern void G__cpp_setup_memvarLinkDef_out();
extern void G__cpp_setup_globalLinkDef_out();
extern void G__cpp_setup_memfuncLinkDef_out();
extern void G__cpp_setup_funcLinkDef_out();
extern void G__set_cpp_environmentLinkDef_out();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/code/osgcode/UCSD_root/root_v5.28.00/include/Math/QuantFuncMathCore.h"
#include "/code/osgcode/UCSD_root/root_v5.28.00/include/TLorentzVector.h"
#include "/code/osgcode/UCSD_root/root_v5.28.00/include/Math/Vector4D.h"
#include "GBRForest.h"
#include "GBRTree.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LinkDef_outLN_TClass;
extern G__linked_taginfo G__LinkDef_outLN_TBuffer;
extern G__linked_taginfo G__LinkDef_outLN_TMemberInspector;
extern G__linked_taginfo G__LinkDef_outLN_TObject;
extern G__linked_taginfo G__LinkDef_outLN_TNamed;
extern G__linked_taginfo G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDef_outLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LinkDef_outLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__LinkDef_outLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LinkDef_outLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMVA;
extern G__linked_taginfo G__LinkDef_outLN_TMVAcLcLDecisionTree;
extern G__linked_taginfo G__LinkDef_outLN_TMVAcLcLDecisionTreeNode;
extern G__linked_taginfo G__LinkDef_outLN_GBRTree;
extern G__linked_taginfo G__LinkDef_outLN_TMVAcLcLMethodBDT;
extern G__linked_taginfo G__LinkDef_outLN_GBRForest;
extern G__linked_taginfo G__LinkDef_outLN_vectorlEGBRTreemUcOallocatorlEGBRTreemUgRsPgR;
extern G__linked_taginfo G__LinkDef_outLN_reverse_iteratorlEvectorlEGBRTreemUcOallocatorlEGBRTreemUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
