/********************************************************************
* linkdef_out.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error linkdef_out.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtablelinkdef_out();
extern void G__cpp_setup_inheritancelinkdef_out();
extern void G__cpp_setup_typetablelinkdef_out();
extern void G__cpp_setup_memvarlinkdef_out();
extern void G__cpp_setup_globallinkdef_out();
extern void G__cpp_setup_memfunclinkdef_out();
extern void G__cpp_setup_funclinkdef_out();
extern void G__set_cpp_environmentlinkdef_out();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ConfigAndRun.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__linkdef_outLN_TBuffer;
extern G__linked_taginfo G__linkdef_outLN_TObject;
extern G__linked_taginfo G__linkdef_outLN_ROOT;
extern G__linked_taginfo G__linkdef_outLN_basic_istreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__linkdef_outLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__linkdef_outLN_va_list;
extern G__linked_taginfo G__linkdef_outLN_TString;
extern G__linked_taginfo G__linkdef_outLN_Process;
extern G__linked_taginfo G__linkdef_outLN_Sample;
extern G__linked_taginfo G__linkdef_outLN_TSubString;
extern G__linked_taginfo G__linkdef_outLN_TArray;
extern G__linked_taginfo G__linkdef_outLN_TArrayD;
extern G__linked_taginfo G__linkdef_outLN_TArrayC;
extern G__linked_taginfo G__linkdef_outLN_TArrayS;
extern G__linked_taginfo G__linkdef_outLN_TArrayI;
extern G__linked_taginfo G__linkdef_outLN_TArrayF;
extern G__linked_taginfo G__linkdef_outLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__linkdef_outLN_TH1D;
extern G__linked_taginfo G__linkdef_outLN_TH1;
extern G__linked_taginfo G__linkdef_outLN_TH1C;
extern G__linked_taginfo G__linkdef_outLN_TH1S;
extern G__linked_taginfo G__linkdef_outLN_TH1I;
extern G__linked_taginfo G__linkdef_outLN_TH1F;
extern G__linked_taginfo G__linkdef_outLN_DileptonHypType;
extern G__linked_taginfo G__linkdef_outLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__linkdef_outLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__linkdef_outLN_vectorlEunsignedsPlongsPlongcOallocatorlEunsignedsPlongsPlonggRsPgR;
extern G__linked_taginfo G__linkdef_outLN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__linkdef_outLN_vectorlEDileptonHistmUcOallocatorlEDileptonHistmUgRsPgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__linkdef_outLN_TH2C;
extern G__linked_taginfo G__linkdef_outLN_TH2S;
extern G__linked_taginfo G__linkdef_outLN_TH2I;
extern G__linked_taginfo G__linkdef_outLN_TH2F;
extern G__linked_taginfo G__linkdef_outLN_TH2D;
extern G__linked_taginfo G__linkdef_outLN_ROOTcLcLMath;
extern G__linked_taginfo G__linkdef_outLN_ROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgR;
extern G__linked_taginfo G__linkdef_outLN_Looper;
extern G__linked_taginfo G__linkdef_outLN_TH3C;
extern G__linked_taginfo G__linkdef_outLN_TH3S;
extern G__linked_taginfo G__linkdef_outLN_TH3I;
extern G__linked_taginfo G__linkdef_outLN_TH3F;
extern G__linked_taginfo G__linkdef_outLN_TH3D;
extern G__linked_taginfo G__linkdef_outLN_TVector2;
extern G__linked_taginfo G__linkdef_outLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__linkdef_outLN_TVector3;
extern G__linked_taginfo G__linkdef_outLN_TLorentzVector;
extern G__linked_taginfo G__linkdef_outLN_vectorlETLorentzVectorcOallocatorlETLorentzVectorgRsPgR;
extern G__linked_taginfo G__linkdef_outLN_vectorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRcOallocatorlEROOTcLcLMathcLcLLorentzVectorlEROOTcLcLMathcLcLPxPyPzE4DlEdoublegRsPgRsPgRsPgR;
extern G__linked_taginfo G__linkdef_outLN_DorkyEventIdentifier;
extern G__linked_taginfo G__linkdef_outLN_setlEDorkyEventIdentifiercOlesslEDorkyEventIdentifiergRcOallocatorlEDorkyEventIdentifiergRsPgR;

/* STUB derived class for protected member access */
