{
  gSystem->CompileMacro("../../../Smurf/Core/SmurfTree.h","k");
  gSystem->CompileMacro("smurfAnalysis.C","k");

  // SmurfAnalysis a(0.188,"/smurf/data/Run2011_Spring11_SmurfV6/tas-TightLooseFullMET-alljets");
  // SmurfAnalysis a(0.191,"/smurf/data/Run2011_Spring11_SmurfV4/tas-TightLooseFullMET-alljets/");
  // SmurfAnalysis a(0.188,"/smurf/data/Run2011_Spring11_SmurfV6/mitf-alljets/");

  // SmurfAnalysis a(0.191,"/smurf/dmytro/samples/smurf", "files/ww_el_fr_smurfV4.root", "el_fr_v4", "files/ww_mu_fr_smurfV4.root", "mu_fr_m2");
  // a.setGoodRunList("Cert_160404-163869_7TeV_PromptReco_Collisions11_JSON.txt");

  // SmurfAnalysis a(0.962,"/smurf/dmytro/tmp/tas-TightLooseFullMET-alljets/");
  SmurfAnalysis a(0.715,"/smurf/dmytro/tmp/tas-TightLooseFullMET-alljets/");
  // SmurfAnalysis a(0.715,"/smurf/dmytro/tmp/only_soft_muon_tagging/");
  a.setGoodRunList("files/Cert_160404-166861_7TeV_PromptReco_Collisions11_JSON_715ipb.txt");
  // a.setGoodRunList("files/certifiedUCSD.json");

  cout << "\n****************** WW 0-jet Selection *******************\n" << endl;
  // a.useNewCuts_ = true;
  a.measurement_.sig_type = SmurfTree::qqww;
  a.measurement_.type = SmurfAnalysis::WW0Jet;
  a.processSamples();
  a.showYields();
  // a.rOutInEl_ = 0.217;
  // a.rOutInMu_ = 0.227;
  a.rOutInEl_ = 0.25;
  a.rOutInMu_ = 0.25; //a.rOutInEl_
  a.rOutInElRelativeErr_ = 0.5;
  a.rOutInMuRelativeErr_ = 0.5; //a.rOutInElRelativeErr_;
  a.kElMu_ = 0.77;
  // a.showYields(1.);
  // a.estimateFakeBackground();
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.makeReport();
  // return;
  cout << "\n****************** HWW120 Selection *******************\n" << endl;
  a.measurement_.sig_type = SmurfTree::hww120;
  a.measurement_.type = SmurfAnalysis::HWWCutBased0Jet;
  a.processSamples();
  a.showYields();
  // a.estimateFakeBackground();
  a.rOutInEl_ = 0.8;
  a.rOutInMu_ = 0.8;
  a.rOutInElRelativeErr_ = 0.5;
  a.rOutInMuRelativeErr_ = 0.5;
  a.kElMu_ = 0.77;
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.printEvents("hww150.list");
  cout << "\n****************** HWW130 Selection *******************\n" << endl;
  a.measurement_.sig_type = SmurfTree::hww130;
  a.measurement_.type = SmurfAnalysis::HWWCutBased0Jet;
  a.processSamples();
  a.showYields();
  // a.estimateFakeBackground();
  a.rOutInEl_ = 1.7;
  a.rOutInMu_ = 1.7;
  a.rOutInElRelativeErr_ = 0.2;
  a.rOutInMuRelativeErr_ = 0.2;
  a.kElMu_ = 0.77;
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.printEvents("hww150.list");
  cout << "\n****************** HWW140 Selection *******************\n" << endl;
  a.measurement_.sig_type = SmurfTree::hww140;
  a.measurement_.type = SmurfAnalysis::HWWCutBased0Jet;
  a.processSamples();
  a.showYields();
  // a.estimateFakeBackground();
  a.rOutInEl_ = 1.1;
  a.rOutInMu_ = 1.1;
  a.rOutInElRelativeErr_ = 0.2;
  a.rOutInMuRelativeErr_ = 0.2;
  a.kElMu_ = 0.77;
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.printEvents("hww150.list");
  cout << "\n****************** HWW150 Selection *******************\n" << endl;
  a.measurement_.sig_type = SmurfTree::hww150;
  a.measurement_.type = SmurfAnalysis::HWWCutBased0Jet;
  a.processSamples();
  a.showYields();
  // a.estimateFakeBackground();
  a.rOutInEl_ = 0.3;
  a.rOutInMu_ = 0.3;
  a.rOutInElRelativeErr_ = 0.3;
  a.rOutInMuRelativeErr_ = 0.3;
  a.kElMu_ = 0.77;
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.printEvents("hww150.list");
  cout << "\n****************** HWW160 Selection *******************\n" << endl;
  a.measurement_.sig_type = SmurfTree::hww160;
  a.measurement_.type = SmurfAnalysis::HWWCutBased0Jet;
  a.processSamples();
  a.showYields();
  // a.estimateFakeBackground();
  a.rOutInEl_ = 0.4;
  a.rOutInMu_ = 0.4;
  a.rOutInElRelativeErr_ = 0.5;
  a.rOutInMuRelativeErr_ = 0.5;
  a.kElMu_ = 0.77;
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.printEvents("hww150.list");
  cout << "\n****************** HWW170 Selection *******************\n" << endl;
  a.measurement_.sig_type = SmurfTree::hww170;
  a.measurement_.type = SmurfAnalysis::HWWCutBased0Jet;
  a.processSamples();
  a.showYields();
  // a.estimateFakeBackground();
  a.rOutInEl_ = 0.25;
  a.rOutInMu_ = 0.25;
  a.rOutInElRelativeErr_ = 0.5;
  a.rOutInMuRelativeErr_ = 0.5;
  a.kElMu_ = 0.77;
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.printEvents("hww150.list");
  cout << "\n****************** HWW180 Selection *******************\n" << endl;
  a.measurement_.sig_type = SmurfTree::hww180;
  a.measurement_.type = SmurfAnalysis::HWWCutBased0Jet;
  a.processSamples();
  a.showYields();
  // a.estimateFakeBackground();
  a.rOutInEl_ = 0.4;
  a.rOutInMu_ = 0.4;
  a.rOutInElRelativeErr_ = 0.5;
  a.rOutInMuRelativeErr_ = 0.5;
  a.kElMu_ = 0.77;
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.printEvents("hww150.list");
  cout << "\n****************** HWW190 Selection *******************\n" << endl;
  a.measurement_.sig_type = SmurfTree::hww190;
  a.measurement_.type = SmurfAnalysis::HWWCutBased0Jet;
  a.processSamples();
  a.showYields();
  // a.estimateFakeBackground();
  a.rOutInEl_ = 0.3;
  a.rOutInMu_ = 0.3;
  a.rOutInElRelativeErr_ = 0.3;
  a.rOutInMuRelativeErr_ = 0.3;
  a.kElMu_ = 0.77;
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.printEvents("hww150.list");
  cout << "\n****************** HWW200 Selection *******************\n" << endl;
  a.measurement_.sig_type = SmurfTree::hww200;
  a.measurement_.type = SmurfAnalysis::HWWCutBased0Jet;
  a.processSamples();
  a.showYields();
  // a.estimateFakeBackground();
  a.rOutInEl_ = 0.1;
  a.rOutInMu_ = 0.1;
  a.rOutInElRelativeErr_ = 0.5;
  a.rOutInMuRelativeErr_ = 0.5;
  a.kElMu_ = 0.77;
  a.estimateDYBackground();
  // a.estimateTopBackground();
  // a.showYields();
  // a.printEvents("hww150.list");

  return ;
}
