//
{
	gSystem->Load("libTree.so");
	gSystem->Load("libPhysics.so");
	gSystem->Load("libEG.so");
	gSystem->Load("libMathCore.so");
	gSystem->Load("libCMS2NtupleMacrosTools.so");
	//gSystem->Load("libCMS2NtupleMacrosWW.so");
        gSystem->Load("libCMS2NtupleMacrosDSG.so");
}
