{

  gStyle->SetOptStat(1111111);
  gStyle->SetPalette(1,0);
  gROOT->UseCurrentStyle();

  int rebinvalue_pt = 1;
  int rebinvalue_eta = 1;

  TFile *_file0 = TFile::Open("ObservationQCDBinsOdd.root");
  TFile *_file2 = TFile::Open("PredictionQCDBinsOdd.root");

  TCanvas * mupt_em = new TCanvas("mupt","mupt");
  TCanvas * mueta_em = new TCanvas("mueta","mueta");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt30to80_muPt_observed = (TH1F*) ((_file0->Get("QCDpt30to80_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt30to80_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt30to80_muPt_observed->SetLineColor(kRed);
  QCDpt30to80_muPt_observed->SetLineWidth(2.);
  QCDpt30to80_muPt_observed->Draw();
  TH1F* QCDpt30to80_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_muPt"))->Clone("QCDpt30to80_muPt_predicted"));
  QCDpt30to80_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt30to80_muPt_predicted->SetLineColor(kBlue);
  QCDpt30to80_muPt_predicted->SetLineWidth(2.);
  QCDpt30to80_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt30to80_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt30to80.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt30to80_muEta_observed = (TH1F*) ((_file0->Get("QCDpt30to80_muEta"))->Clone("QCDpt30to80_muEta_observed"));
  QCDpt30to80_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt30to80_muEta_observed->SetLineColor(kRed);
  QCDpt30to80_muEta_observed->SetLineWidth(2.);
  QCDpt30to80_muEta_observed->Draw();
  TH1F* QCDpt30to80_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_muEta"))->Clone("QCDpt30to80_muEta_predicted"));
  QCDpt30to80_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt30to80_muEta_predicted->SetLineColor(kBlue);
  QCDpt30to80_muEta_predicted->SetLineWidth(2.);
  QCDpt30to80_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt30to80_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt30to80.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt80to170_muPt_observed = (TH1F*) ((_file0->Get("QCDpt80to170_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt80to170_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt80to170_muPt_observed->SetLineColor(kRed);
  QCDpt80to170_muPt_observed->SetLineWidth(2.);
  QCDpt80to170_muPt_observed->Draw();
  TH1F* QCDpt80to170_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt80to170_muPt"))->Clone("QCDpt80to170_muPt_predicted"));
  QCDpt80to170_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt80to170_muPt_predicted->SetLineColor(kBlue);
  QCDpt80to170_muPt_predicted->SetLineWidth(2.);
  QCDpt80to170_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt80to170_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt80to170.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt80to170_muEta_observed = (TH1F*) ((_file0->Get("QCDpt80to170_muEta"))->Clone("QCDpt80to170_muEta_observed"));
  QCDpt80to170_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt80to170_muEta_observed->SetLineColor(kRed);
  QCDpt80to170_muEta_observed->SetLineWidth(2.);
  QCDpt80to170_muEta_observed->Draw();
  TH1F* QCDpt80to170_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt80to170_muEta"))->Clone("QCDpt80to170_muEta_predicted"));
  QCDpt80to170_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt80to170_muEta_predicted->SetLineColor(kBlue);
  QCDpt80to170_muEta_predicted->SetLineWidth(2.);
  QCDpt80to170_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt80to170_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt80to170.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt170to300_muPt_observed = (TH1F*) ((_file0->Get("QCDpt170to300_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt170to300_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt170to300_muPt_observed->SetLineColor(kRed);
  QCDpt170to300_muPt_observed->SetLineWidth(2.);
  QCDpt170to300_muPt_observed->Draw();
  TH1F* QCDpt170to300_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt170to300_muPt"))->Clone("QCDpt170to300_muPt_predicted"));
  QCDpt170to300_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt170to300_muPt_predicted->SetLineColor(kBlue);
  QCDpt170to300_muPt_predicted->SetLineWidth(2.);
  QCDpt170to300_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt170to300_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt170to300.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt170to300_muEta_observed = (TH1F*) ((_file0->Get("QCDpt170to300_muEta"))->Clone("QCDpt170to300_muEta_observed"));
  QCDpt170to300_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt170to300_muEta_observed->SetLineColor(kRed);
  QCDpt170to300_muEta_observed->SetLineWidth(2.);
  QCDpt170to300_muEta_observed->Draw();
  TH1F* QCDpt170to300_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt170to300_muEta"))->Clone("QCDpt170to300_muEta_predicted"));
  QCDpt170to300_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt170to300_muEta_predicted->SetLineColor(kBlue);
  QCDpt170to300_muEta_predicted->SetLineWidth(2.);
  QCDpt170to300_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt170to300_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt170to300.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt300to470_muPt_observed = (TH1F*) ((_file0->Get("QCDpt300to470_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt300to470_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt300to470_muPt_observed->SetLineColor(kRed);
  QCDpt300to470_muPt_observed->SetLineWidth(2.);
  QCDpt300to470_muPt_observed->Draw();
  TH1F* QCDpt300to470_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt300to470_muPt"))->Clone("QCDpt300to470_muPt_predicted"));
  QCDpt300to470_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt300to470_muPt_predicted->SetLineColor(kBlue);
  QCDpt300to470_muPt_predicted->SetLineWidth(2.);
  QCDpt300to470_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt300to470_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt300to470.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt300to470_muEta_observed = (TH1F*) ((_file0->Get("QCDpt300to470_muEta"))->Clone("QCDpt300to470_muEta_observed"));
  QCDpt300to470_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt300to470_muEta_observed->SetLineColor(kRed);
  QCDpt300to470_muEta_observed->SetLineWidth(2.);
  QCDpt300to470_muEta_observed->Draw();
  TH1F* QCDpt300to470_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt300to470_muEta"))->Clone("QCDpt300to470_muEta_predicted"));
  QCDpt300to470_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt300to470_muEta_predicted->SetLineColor(kBlue);
  QCDpt300to470_muEta_predicted->SetLineWidth(2.);
  QCDpt300to470_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt300to470_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt300to470.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt470to800_muPt_observed = (TH1F*) ((_file0->Get("QCDpt470to800_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt470to800_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt470to800_muPt_observed->SetLineColor(kRed);
  QCDpt470to800_muPt_observed->SetLineWidth(2.);
  QCDpt470to800_muPt_observed->Draw();
  TH1F* QCDpt470to800_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt470to800_muPt"))->Clone("QCDpt470to800_muPt_predicted"));
  QCDpt470to800_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt470to800_muPt_predicted->SetLineColor(kBlue);
  QCDpt470to800_muPt_predicted->SetLineWidth(2.);
  QCDpt470to800_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt470to800_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt470to800.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt470to800_muEta_observed = (TH1F*) ((_file0->Get("QCDpt470to800_muEta"))->Clone("QCDpt470to800_muEta_observed"));
  QCDpt470to800_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt470to800_muEta_observed->SetLineColor(kRed);
  QCDpt470to800_muEta_observed->SetLineWidth(2.);
  QCDpt470to800_muEta_observed->Draw();
  TH1F* QCDpt470to800_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt470to800_muEta"))->Clone("QCDpt470to800_muEta_predicted"));
  QCDpt470to800_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt470to800_muEta_predicted->SetLineColor(kBlue);
  QCDpt470to800_muEta_predicted->SetLineWidth(2.);
  QCDpt470to800_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt470to800_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt470to800.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt800toInf_muPt_observed = (TH1F*) ((_file0->Get("QCDpt800toInf_muPt"))->Clone("QCDpt800tpInf_muPt_observed"));
  QCDpt800toInf_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt800toInf_muPt_observed->SetLineColor(kRed);
  QCDpt800toInf_muPt_observed->SetLineWidth(2.);
  QCDpt800toInf_muPt_observed->Draw();
  TH1F* QCDpt800toInf_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt800toInf_muPt"))->Clone("QCDpt800toInf_muPt_predicted"));
  QCDpt800toInf_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt800toInf_muPt_predicted->SetLineColor(kBlue);
  QCDpt800toInf_muPt_predicted->SetLineWidth(2.);
  QCDpt800toInf_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt800toInf_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt800toInf.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt800toInf_muEta_observed = (TH1F*) ((_file0->Get("QCDpt800toInf_muEta"))->Clone("QCDpt800toInf_muEta_observed"));
  QCDpt800toInf_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt800toInf_muEta_observed->SetLineColor(kRed);
  QCDpt800toInf_muEta_observed->SetLineWidth(2.);
  QCDpt800toInf_muEta_observed->Draw();
  TH1F* QCDpt800toInf_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt800toInf_muEta"))->Clone("QCDpt800toInf_muEta_predicted"));
  QCDpt800toInf_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt800toInf_muEta_predicted->SetLineColor(kBlue);
  QCDpt800toInf_muEta_predicted->SetLineWidth(2.);
  QCDpt800toInf_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt800toInf_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt800toInf.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* muPt_observed = (TH1F*) ((_file0->Get("QCDpt30to80_muPt"))->Clone("muPt_observed"));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt80to170_muPt"))));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt170to300_muPt"))));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt300to470_muPt"))));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt470to800_muPt"))));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt800toInf_muPt"))));
  muPt_observed->Rebin(rebinvalue_pt);
  muPt_observed->SetLineColor(kRed);
  muPt_observed->SetLineWidth(2.);
  TH1F* muPt_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_muPt"))->Clone("muPt_predicted"));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt80to170_muPt"))));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt170to300_muPt"))));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt300to470_muPt"))));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt470to800_muPt"))));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt800toInf_muPt"))));
  muPt_predicted->Rebin(rebinvalue_pt);
  muPt_predicted->SetLineColor(kBlue);
  muPt_predicted->SetLineWidth(2.);
  muPt_predicted->Draw();
  muPt_observed->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* muEta_observed = (TH1F*) ((_file0->Get("QCDpt30to80_muEta"))->Clone("muEta_observed"));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt80to170_muEta"))));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt170to300_muEta"))));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt300to470_muEta"))));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt470to800_muEta"))));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt800toInf_muEta"))));
  muEta_observed->Rebin(rebinvalue_eta);
  muEta_observed->SetLineColor(kRed);
  muEta_observed->SetLineWidth(2.);
  TH1F* muEta_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_muEta"))->Clone("muEta_predicted"));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt80to170_muEta"))));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt170to300_muEta"))));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt300to470_muEta"))));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt470to800_muEta"))));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt800toInf_muEta"))));
  muEta_predicted->Rebin(rebinvalue_eta);
  muEta_predicted->SetLineColor(kBlue);
  muEta_predicted->SetLineWidth(2.);
  muEta_predicted->Draw();
  muEta_observed->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta.png");

}
