{
  
  gROOT->SetStyle("Plain");
  gStyle->SetOptStat(1111111);
  gStyle->SetOptTitle(0);
  gStyle->SetPalette(1,0);

  gStyle->SetPadLeftMargin(0.12);
  gStyle->SetPadBottomMargin(0.12);

  gROOT->UseCurrentStyle();

  int rebinvalue_pt = 1;
  int rebinvalue_eta = 1;

  TFile *_file0 = TFile::Open("ObservationQCDBinsOdd.root");
  TFile *_file2 = TFile::Open("PredictionQCDBinsOdd.root");

  TCanvas * mupt_em = new TCanvas("mupt","mupt");
  TCanvas * mueta_em = new TCanvas("mueta","mueta");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt30to80_muPt_observed = (TH1F*) ((_file0->Get("QCDpt30to80_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt30to80_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt30to80_muPt_observed->SetLineColor(kRed);
  QCDpt30to80_muPt_observed->SetLineWidth(2.);
  QCDpt30to80_muPt_observed->Draw();
  TH1F* QCDpt30to80_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_muPt"))->Clone("QCDpt30to80_muPt_predicted"));
  QCDpt30to80_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt30to80_muPt_predicted->SetLineColor(kBlue);
  QCDpt30to80_muPt_predicted->SetLineWidth(2.);
  QCDpt30to80_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt30to80_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt30to80.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt30to80_muEta_observed = (TH1F*) ((_file0->Get("QCDpt30to80_muEta"))->Clone("QCDpt30to80_muEta_observed"));
  QCDpt30to80_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt30to80_muEta_observed->SetLineColor(kRed);
  QCDpt30to80_muEta_observed->SetLineWidth(2.);
  QCDpt30to80_muEta_observed->Draw();
  TH1F* QCDpt30to80_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_muEta"))->Clone("QCDpt30to80_muEta_predicted"));
  QCDpt30to80_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt30to80_muEta_predicted->SetLineColor(kBlue);
  QCDpt30to80_muEta_predicted->SetLineWidth(2.);
  QCDpt30to80_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt30to80_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt30to80.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt80to170_muPt_observed = (TH1F*) ((_file0->Get("QCDpt80to170_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt80to170_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt80to170_muPt_observed->SetLineColor(kRed);
  QCDpt80to170_muPt_observed->SetLineWidth(2.);
  QCDpt80to170_muPt_observed->Draw();
  TH1F* QCDpt80to170_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt80to170_muPt"))->Clone("QCDpt80to170_muPt_predicted"));
  QCDpt80to170_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt80to170_muPt_predicted->SetLineColor(kBlue);
  QCDpt80to170_muPt_predicted->SetLineWidth(2.);
  QCDpt80to170_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt80to170_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt80to170.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt80to170_muEta_observed = (TH1F*) ((_file0->Get("QCDpt80to170_muEta"))->Clone("QCDpt80to170_muEta_observed"));
  QCDpt80to170_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt80to170_muEta_observed->SetLineColor(kRed);
  QCDpt80to170_muEta_observed->SetLineWidth(2.);
  QCDpt80to170_muEta_observed->Draw();
  TH1F* QCDpt80to170_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt80to170_muEta"))->Clone("QCDpt80to170_muEta_predicted"));
  QCDpt80to170_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt80to170_muEta_predicted->SetLineColor(kBlue);
  QCDpt80to170_muEta_predicted->SetLineWidth(2.);
  QCDpt80to170_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt80to170_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt80to170.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt170to300_muPt_observed = (TH1F*) ((_file0->Get("QCDpt170to300_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt170to300_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt170to300_muPt_observed->SetLineColor(kRed);
  QCDpt170to300_muPt_observed->SetLineWidth(2.);
  QCDpt170to300_muPt_observed->Draw();
  TH1F* QCDpt170to300_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt170to300_muPt"))->Clone("QCDpt170to300_muPt_predicted"));
  QCDpt170to300_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt170to300_muPt_predicted->SetLineColor(kBlue);
  QCDpt170to300_muPt_predicted->SetLineWidth(2.);
  QCDpt170to300_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt170to300_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt170to300.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt170to300_muEta_observed = (TH1F*) ((_file0->Get("QCDpt170to300_muEta"))->Clone("QCDpt170to300_muEta_observed"));
  QCDpt170to300_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt170to300_muEta_observed->SetLineColor(kRed);
  QCDpt170to300_muEta_observed->SetLineWidth(2.);
  QCDpt170to300_muEta_observed->Draw();
  TH1F* QCDpt170to300_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt170to300_muEta"))->Clone("QCDpt170to300_muEta_predicted"));
  QCDpt170to300_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt170to300_muEta_predicted->SetLineColor(kBlue);
  QCDpt170to300_muEta_predicted->SetLineWidth(2.);
  QCDpt170to300_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt170to300_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt170to300.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt300to470_muPt_observed = (TH1F*) ((_file0->Get("QCDpt300to470_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt300to470_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt300to470_muPt_observed->SetLineColor(kRed);
  QCDpt300to470_muPt_observed->SetLineWidth(2.);
  QCDpt300to470_muPt_observed->Draw();
  TH1F* QCDpt300to470_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt300to470_muPt"))->Clone("QCDpt300to470_muPt_predicted"));
  QCDpt300to470_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt300to470_muPt_predicted->SetLineColor(kBlue);
  QCDpt300to470_muPt_predicted->SetLineWidth(2.);
  QCDpt300to470_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt300to470_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt300to470.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt300to470_muEta_observed = (TH1F*) ((_file0->Get("QCDpt300to470_muEta"))->Clone("QCDpt300to470_muEta_observed"));
  QCDpt300to470_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt300to470_muEta_observed->SetLineColor(kRed);
  QCDpt300to470_muEta_observed->SetLineWidth(2.);
  QCDpt300to470_muEta_observed->Draw();
  TH1F* QCDpt300to470_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt300to470_muEta"))->Clone("QCDpt300to470_muEta_predicted"));
  QCDpt300to470_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt300to470_muEta_predicted->SetLineColor(kBlue);
  QCDpt300to470_muEta_predicted->SetLineWidth(2.);
  QCDpt300to470_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt300to470_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt300to470.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt470to800_muPt_observed = (TH1F*) ((_file0->Get("QCDpt470to800_muPt"))->Clone("QCDpt30tp80_muPt_observed"));
  QCDpt470to800_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt470to800_muPt_observed->SetLineColor(kRed);
  QCDpt470to800_muPt_observed->SetLineWidth(2.);
  QCDpt470to800_muPt_observed->Draw();
  TH1F* QCDpt470to800_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt470to800_muPt"))->Clone("QCDpt470to800_muPt_predicted"));
  QCDpt470to800_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt470to800_muPt_predicted->SetLineColor(kBlue);
  QCDpt470to800_muPt_predicted->SetLineWidth(2.);
  QCDpt470to800_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt470to800_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt470to800.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt470to800_muEta_observed = (TH1F*) ((_file0->Get("QCDpt470to800_muEta"))->Clone("QCDpt470to800_muEta_observed"));
  QCDpt470to800_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt470to800_muEta_observed->SetLineColor(kRed);
  QCDpt470to800_muEta_observed->SetLineWidth(2.);
  QCDpt470to800_muEta_observed->Draw();
  TH1F* QCDpt470to800_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt470to800_muEta"))->Clone("QCDpt470to800_muEta_predicted"));
  QCDpt470to800_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt470to800_muEta_predicted->SetLineColor(kBlue);
  QCDpt470to800_muEta_predicted->SetLineWidth(2.);
  QCDpt470to800_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt470to800_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt470to800.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* QCDpt800toInf_muPt_observed = (TH1F*) ((_file0->Get("QCDpt800toInf_muPt"))->Clone("QCDpt800tpInf_muPt_observed"));
  QCDpt800toInf_muPt_observed->Rebin(rebinvalue_pt);
  QCDpt800toInf_muPt_observed->SetLineColor(kRed);
  QCDpt800toInf_muPt_observed->SetLineWidth(2.);
  QCDpt800toInf_muPt_observed->Draw();
  TH1F* QCDpt800toInf_muPt_predicted = (TH1F*) ((_file2->Get("QCDpt800toInf_muPt"))->Clone("QCDpt800toInf_muPt_predicted"));
  QCDpt800toInf_muPt_predicted->Rebin(rebinvalue_pt);
  QCDpt800toInf_muPt_predicted->SetLineColor(kBlue);
  QCDpt800toInf_muPt_predicted->SetLineWidth(2.);
  QCDpt800toInf_muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(QCDpt800toInf_muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.78);
  stats_mupt->SetY1NDC(0.43);
  stats_mupt->SetX2NDC(0.98);
  stats_mupt->SetY2NDC(0.71);
  mupt->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  mupt->SaveAs("mu_pt_QCDpt800toInf.png");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* QCDpt800toInf_muEta_observed = (TH1F*) ((_file0->Get("QCDpt800toInf_muEta"))->Clone("QCDpt800toInf_muEta_observed"));
  QCDpt800toInf_muEta_observed->Rebin(rebinvalue_eta);
  QCDpt800toInf_muEta_observed->SetLineColor(kRed);
  QCDpt800toInf_muEta_observed->SetLineWidth(2.);
  QCDpt800toInf_muEta_observed->Draw();
  TH1F* QCDpt800toInf_muEta_predicted = (TH1F*) ((_file2->Get("QCDpt800toInf_muEta"))->Clone("QCDpt800toInf_muEta_predicted"));
  QCDpt800toInf_muEta_predicted->Rebin(rebinvalue_eta);
  QCDpt800toInf_muEta_predicted->SetLineColor(kBlue);
  QCDpt800toInf_muEta_predicted->SetLineWidth(2.);
  QCDpt800toInf_muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_mueta = (TPaveStats*)(QCDpt800toInf_muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mueta->SetX1NDC(0.78);
  stats_mueta->SetY1NDC(0.43);
  stats_mueta->SetX2NDC(0.98);
  stats_mueta->SetY2NDC(0.71);
  mueta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  mueta->SaveAs("mu_eta_QCDpt800toInf.png");

  // plot Pt comparison
  mupt->cd();
  mupt->Clear();
  TH1F* muPt_observed = (TH1F*) ((_file0->Get("QCDpt30to80_muPt"))->Clone("muPt_observed"));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt80to170_muPt"))));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt170to300_muPt"))));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt300to470_muPt"))));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt470to800_muPt"))));
  muPt_observed->Add(((TH1F*)(_file0->Get("QCDpt800toInf_muPt"))));
  muPt_observed->Rebin(rebinvalue_pt);
  muPt_observed->SetLineColor(kRed);
  muPt_observed->SetFillColor(kWhite);
  muPt_observed->SetLineWidth(2.);
  muPt_observed->SetName("observed");
  muPt_observed->GetYaxis()->SetTitle("Events");
  muPt_observed->GetYaxis()->SetTitleOffset(1.2);
  muPt_observed->GetYaxis()->SetTitleSize(0.04);
  muPt_observed->GetXaxis()->SetTitle("p_{T}^{electron} (GeV)");
  muPt_observed->GetXaxis()->SetTitleOffset(1.2);
  muPt_observed->GetXaxis()->SetTitleSize(0.04);
  muPt_observed->SetMarkerStyle(20);
  muPt_observed->SetMarkerColor(kRed);
  muPt_observed->SetMarkerSize(1.1);
  TH1F* muPt_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_muPt"))->Clone("muPt_predicted"));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt80to170_muPt"))));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt170to300_muPt"))));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt300to470_muPt"))));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt470to800_muPt"))));
  muPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt800toInf_muPt"))));
  muPt_predicted->Rebin(rebinvalue_pt);
  muPt_predicted->SetLineColor(kBlue);
  muPt_predicted->SetFillColor(kWhite);
  muPt_predicted->SetLineWidth(2.);
  muPt_predicted->SetName("predicted");
  muPt_predicted->SetMarkerStyle(28);
  muPt_predicted->SetMarkerColor(kBlue);
  muPt_predicted->SetMarkerSize(1.2);
//   muPt_predicted->Draw();
//   muPt_observed->Draw("sames");
//   double MaxBuffer = muPt_predicted->GetMaximum();
//   muPt_observed->SetMaximum(1.2*MaxBuffer);
  muPt_observed->Draw();
  muPt_predicted->Draw("sames");
  mupt->Update();
  TPaveStats *stats_mupt = (TPaveStats*)(muPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_mupt->SetX1NDC(0.8 );
  stats_mupt->SetY1NDC(0.5 );
  stats_mupt->SetX2NDC(0.99);
  stats_mupt->SetY2NDC(0.74);
  TPaveStats *stats_mupt2 = (TPaveStats*)(muPt_observed->GetListOfFunctions()->FindObject("stats"));
  stats_mupt2->SetX1NDC(0.8 );
  stats_mupt2->SetY1NDC(0.75);
  stats_mupt2->SetX2NDC(0.99);
  stats_mupt2->SetY2NDC(0.99);
  mupt->Update();
//   TLatex *   lable_ref = new TLatex(0.55,0.75,"");
//   lable_ref->SetNDC();
//   lable_ref->SetTextSize(0.04);
//   lable_ref->SetTextColor(kRed);
//   TLatex *   lable_new = new TLatex(0.55,0.7,"");
//   lable_new->SetNDC();
//   lable_new->SetTextSize(0.04);
//   lable_new->SetTextColor(kBlue);
//   lable_new->Draw();
//   lable_ref->Draw();
  leg = new TLegend(0.5,0.75,0.79,0.99,NULL,"brNDC");
  leg->SetLineColor(1);
  leg->SetLineStyle(1);
  leg->SetLineWidth(1);
  leg->SetFillColor(10);
  leg->SetBorderSize(1);
  //  leg->SetHeader(                               "L1 CSC trigger efficiency - With ME42");
  leg->AddEntry(muPt_observed,       "Observed","lpf");
  leg->AddEntry(muPt_predicted,      "Predicted","lpf");
  leg->Draw();

  mupt->SaveAs("muo_pt.png");
  mupt->Print("muo_pt.pdf");

  // Plot eta comparison
  mueta->cd();
  mueta->Clear();
  TH1F* muEta_observed = (TH1F*) ((_file0->Get("QCDpt30to80_muEta"))->Clone("muEta_observed"));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt80to170_muEta"))));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt170to300_muEta"))));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt300to470_muEta"))));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt470to800_muEta"))));
  muEta_observed->Add(((TH1F*)(_file0->Get("QCDpt800toInf_muEta"))));
  muEta_observed->Rebin(rebinvalue_eta);
  muEta_observed->SetLineColor(kRed);
  muEta_observed->SetFillColor(kWhite);
  muEta_observed->SetLineWidth(2.);
  muEta_observed->SetName("observed");
  muEta_observed->GetYaxis()->SetTitle("Events");
  muEta_observed->GetYaxis()->SetTitleOffset(1.2);
  muEta_observed->GetYaxis()->SetTitleSize(0.04);
  muEta_observed->GetXaxis()->SetTitle("p_{T}^{electron} (GeV)");
  muEta_observed->GetXaxis()->SetTitleOffset(1.2);
  muEta_observed->GetXaxis()->SetTitleSize(0.04);
  muEta_observed->SetMarkerStyle(20);
  muEta_observed->SetMarkerColor(kRed);
  muEta_observed->SetMarkerSize(1.1);
  TH1F* muEta_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_muEta"))->Clone("muEta_predicted"));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt80to170_muEta"))));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt170to300_muEta"))));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt300to470_muEta"))));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt470to800_muEta"))));
  muEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt800toInf_muEta"))));
  muEta_predicted->Rebin(rebinvalue_eta);
  muEta_predicted->SetLineColor(kBlue);
  muEta_predicted->SetFillColor(kWhite);
  muEta_predicted->SetLineWidth(2.);
  muEta_predicted->SetName("predicted");
  muEta_predicted->SetMarkerStyle(28);
  muEta_predicted->SetMarkerColor(kBlue);
  muEta_predicted->SetMarkerSize(1.2);
  muEta_observed->Draw();
  muEta_predicted->Draw("sames");
  mueta->Update();
  TPaveStats *stats_eleta = (TPaveStats*)(muEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_eleta->SetX1NDC(0.8 );
  stats_eleta->SetY1NDC(0.5 );
  stats_eleta->SetX2NDC(0.99);
  stats_eleta->SetY2NDC(0.74);
  TPaveStats *stats_eleta2 = (TPaveStats*)(muEta_observed->GetListOfFunctions()->FindObject("stats"));
  stats_eleta2->SetX1NDC(0.8 );
  stats_eleta2->SetY1NDC(0.75);
  stats_eleta2->SetX2NDC(0.99);
  stats_eleta2->SetY2NDC(0.99);
  mueta->Update();
//   lable_new->Draw();
//   lable_ref->Draw();
  leg2 = new TLegend(0.5,0.75,0.79,0.99,NULL,"brNDC");
  leg2->SetLineColor(1);
  leg2->SetLineStyle(1);
  leg2->SetLineWidth(1);
  leg2->SetFillColor(10);
  leg2->SetBorderSize(1);
  //  leg2->SetHeader(                               "L1 CSC trigger efficiency - With ME42");
  leg2->AddEntry(muEta_observed,       "Observed","lpf");
  leg2->AddEntry(muEta_predicted,      "Predicted","lpf");
  leg2->Draw();
  mueta->SaveAs("muo_eta.png");
  mueta->Print("muo_eta.pdf");

}
