{

  gStyle->SetOptStat(1111111);
  gStyle->SetPalette(1,0);
  gROOT->UseCurrentStyle();

  int rebinvalue_pt = 1;
  int rebinvalue_eta = 1;

  TFile *_file0 = TFile::Open("ObservationQCDBinsOdd.root");
  TFile *_file2 = TFile::Open("PredictionQCDBinsOdd.root");

  TCanvas * elept_em = new TCanvas("elept","elept");
  TCanvas * eleeta_em = new TCanvas("eleeta","eleeta");

  // plot Pt comparison
  elept->cd();
  elept->Clear();
  TH1F* QCDpt30to80_elPt_observed = (TH1F*) ((_file0->Get("QCDpt30to80_elPt"))->Clone("QCDpt30tp80_elPt_observed"));
  QCDpt30to80_elPt_observed->Rebin(rebinvalue_pt);
  QCDpt30to80_elPt_observed->SetLineColor(kRed);
  QCDpt30to80_elPt_observed->SetLineWidth(2.);
  QCDpt30to80_elPt_observed->Draw();
  TH1F* QCDpt30to80_elPt_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_elPt"))->Clone("QCDpt30to80_elPt_predicted"));
  QCDpt30to80_elPt_predicted->Rebin(rebinvalue_pt);
  QCDpt30to80_elPt_predicted->SetLineColor(kBlue);
  QCDpt30to80_elPt_predicted->SetLineWidth(2.);
  QCDpt30to80_elPt_predicted->Draw("sames");
  elept->Update();
  TPaveStats *stats_elpt = (TPaveStats*)(QCDpt30to80_elPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_elpt->SetX1NDC(0.78);
  stats_elpt->SetY1NDC(0.43);
  stats_elpt->SetX2NDC(0.98);
  stats_elpt->SetY2NDC(0.71);
  elept->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  elept->SaveAs("ele_pt_QCDpt30to80.png");

  // Plot eta comparison
  eleeta->cd();
  eleeta->Clear();
  TH1F* QCDpt30to80_elEta_observed = (TH1F*) ((_file0->Get("QCDpt30to80_elEta"))->Clone("QCDpt30to80_elEta_observed"));
  QCDpt30to80_elEta_observed->Rebin(rebinvalue_eta);
  QCDpt30to80_elEta_observed->SetLineColor(kRed);
  QCDpt30to80_elEta_observed->SetLineWidth(2.);
  QCDpt30to80_elEta_observed->Draw();
  TH1F* QCDpt30to80_elEta_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_elEta"))->Clone("QCDpt30to80_elEta_predicted"));
  QCDpt30to80_elEta_predicted->Rebin(rebinvalue_eta);
  QCDpt30to80_elEta_predicted->SetLineColor(kBlue);
  QCDpt30to80_elEta_predicted->SetLineWidth(2.);
  QCDpt30to80_elEta_predicted->Draw("sames");
  eleeta->Update();
  TPaveStats *stats_eleeta = (TPaveStats*)(QCDpt30to80_elEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_eleeta->SetX1NDC(0.78);
  stats_eleeta->SetY1NDC(0.43);
  stats_eleeta->SetX2NDC(0.98);
  stats_eleeta->SetY2NDC(0.71);
  eleeta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  eleeta->SaveAs("ele_eta_QCDpt30to80.png");

  // plot Pt comparison
  elept->cd();
  elept->Clear();
  TH1F* QCDpt80to170_elPt_observed = (TH1F*) ((_file0->Get("QCDpt80to170_elPt"))->Clone("QCDpt30tp80_elPt_observed"));
  QCDpt80to170_elPt_observed->Rebin(rebinvalue_pt);
  QCDpt80to170_elPt_observed->SetLineColor(kRed);
  QCDpt80to170_elPt_observed->SetLineWidth(2.);
  QCDpt80to170_elPt_observed->Draw();
  TH1F* QCDpt80to170_elPt_predicted = (TH1F*) ((_file2->Get("QCDpt80to170_elPt"))->Clone("QCDpt80to170_elPt_predicted"));
  QCDpt80to170_elPt_predicted->Rebin(rebinvalue_pt);
  QCDpt80to170_elPt_predicted->SetLineColor(kBlue);
  QCDpt80to170_elPt_predicted->SetLineWidth(2.);
  QCDpt80to170_elPt_predicted->Draw("sames");
  elept->Update();
  TPaveStats *stats_elpt = (TPaveStats*)(QCDpt80to170_elPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_elpt->SetX1NDC(0.78);
  stats_elpt->SetY1NDC(0.43);
  stats_elpt->SetX2NDC(0.98);
  stats_elpt->SetY2NDC(0.71);
  elept->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  elept->SaveAs("ele_pt_QCDpt80to170.png");

  // Plot eta comparison
  eleeta->cd();
  eleeta->Clear();
  TH1F* QCDpt80to170_elEta_observed = (TH1F*) ((_file0->Get("QCDpt80to170_elEta"))->Clone("QCDpt80to170_elEta_observed"));
  QCDpt80to170_elEta_observed->Rebin(rebinvalue_eta);
  QCDpt80to170_elEta_observed->SetLineColor(kRed);
  QCDpt80to170_elEta_observed->SetLineWidth(2.);
  QCDpt80to170_elEta_observed->Draw();
  TH1F* QCDpt80to170_elEta_predicted = (TH1F*) ((_file2->Get("QCDpt80to170_elEta"))->Clone("QCDpt80to170_elEta_predicted"));
  QCDpt80to170_elEta_predicted->Rebin(rebinvalue_eta);
  QCDpt80to170_elEta_predicted->SetLineColor(kBlue);
  QCDpt80to170_elEta_predicted->SetLineWidth(2.);
  QCDpt80to170_elEta_predicted->Draw("sames");
  eleeta->Update();
  TPaveStats *stats_eleeta = (TPaveStats*)(QCDpt80to170_elEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_eleeta->SetX1NDC(0.78);
  stats_eleeta->SetY1NDC(0.43);
  stats_eleeta->SetX2NDC(0.98);
  stats_eleeta->SetY2NDC(0.71);
  eleeta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  eleeta->SaveAs("ele_eta_QCDpt80to170.png");

  // plot Pt comparison
  elept->cd();
  elept->Clear();
  TH1F* QCDpt170to300_elPt_observed = (TH1F*) ((_file0->Get("QCDpt170to300_elPt"))->Clone("QCDpt30tp80_elPt_observed"));
  QCDpt170to300_elPt_observed->Rebin(rebinvalue_pt);
  QCDpt170to300_elPt_observed->SetLineColor(kRed);
  QCDpt170to300_elPt_observed->SetLineWidth(2.);
  QCDpt170to300_elPt_observed->Draw();
  TH1F* QCDpt170to300_elPt_predicted = (TH1F*) ((_file2->Get("QCDpt170to300_elPt"))->Clone("QCDpt170to300_elPt_predicted"));
  QCDpt170to300_elPt_predicted->Rebin(rebinvalue_pt);
  QCDpt170to300_elPt_predicted->SetLineColor(kBlue);
  QCDpt170to300_elPt_predicted->SetLineWidth(2.);
  QCDpt170to300_elPt_predicted->Draw("sames");
  elept->Update();
  TPaveStats *stats_elpt = (TPaveStats*)(QCDpt170to300_elPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_elpt->SetX1NDC(0.78);
  stats_elpt->SetY1NDC(0.43);
  stats_elpt->SetX2NDC(0.98);
  stats_elpt->SetY2NDC(0.71);
  elept->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  elept->SaveAs("ele_pt_QCDpt170to300.png");

  // Plot eta comparison
  eleeta->cd();
  eleeta->Clear();
  TH1F* QCDpt170to300_elEta_observed = (TH1F*) ((_file0->Get("QCDpt170to300_elEta"))->Clone("QCDpt170to300_elEta_observed"));
  QCDpt170to300_elEta_observed->Rebin(rebinvalue_eta);
  QCDpt170to300_elEta_observed->SetLineColor(kRed);
  QCDpt170to300_elEta_observed->SetLineWidth(2.);
  QCDpt170to300_elEta_observed->Draw();
  TH1F* QCDpt170to300_elEta_predicted = (TH1F*) ((_file2->Get("QCDpt170to300_elEta"))->Clone("QCDpt170to300_elEta_predicted"));
  QCDpt170to300_elEta_predicted->Rebin(rebinvalue_eta);
  QCDpt170to300_elEta_predicted->SetLineColor(kBlue);
  QCDpt170to300_elEta_predicted->SetLineWidth(2.);
  QCDpt170to300_elEta_predicted->Draw("sames");
  eleeta->Update();
  TPaveStats *stats_eleeta = (TPaveStats*)(QCDpt170to300_elEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_eleeta->SetX1NDC(0.78);
  stats_eleeta->SetY1NDC(0.43);
  stats_eleeta->SetX2NDC(0.98);
  stats_eleeta->SetY2NDC(0.71);
  eleeta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  eleeta->SaveAs("ele_eta_QCDpt170to300.png");

  // plot Pt comparison
  elept->cd();
  elept->Clear();
  TH1F* QCDpt300to470_elPt_observed = (TH1F*) ((_file0->Get("QCDpt300to470_elPt"))->Clone("QCDpt30tp80_elPt_observed"));
  QCDpt300to470_elPt_observed->Rebin(rebinvalue_pt);
  QCDpt300to470_elPt_observed->SetLineColor(kRed);
  QCDpt300to470_elPt_observed->SetLineWidth(2.);
  QCDpt300to470_elPt_observed->Draw();
  TH1F* QCDpt300to470_elPt_predicted = (TH1F*) ((_file2->Get("QCDpt300to470_elPt"))->Clone("QCDpt300to470_elPt_predicted"));
  QCDpt300to470_elPt_predicted->Rebin(rebinvalue_pt);
  QCDpt300to470_elPt_predicted->SetLineColor(kBlue);
  QCDpt300to470_elPt_predicted->SetLineWidth(2.);
  QCDpt300to470_elPt_predicted->Draw("sames");
  elept->Update();
  TPaveStats *stats_elpt = (TPaveStats*)(QCDpt300to470_elPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_elpt->SetX1NDC(0.78);
  stats_elpt->SetY1NDC(0.43);
  stats_elpt->SetX2NDC(0.98);
  stats_elpt->SetY2NDC(0.71);
  elept->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  elept->SaveAs("ele_pt_QCDpt300to470.png");

  // Plot eta comparison
  eleeta->cd();
  eleeta->Clear();
  TH1F* QCDpt300to470_elEta_observed = (TH1F*) ((_file0->Get("QCDpt300to470_elEta"))->Clone("QCDpt300to470_elEta_observed"));
  QCDpt300to470_elEta_observed->Rebin(rebinvalue_eta);
  QCDpt300to470_elEta_observed->SetLineColor(kRed);
  QCDpt300to470_elEta_observed->SetLineWidth(2.);
  QCDpt300to470_elEta_observed->Draw();
  TH1F* QCDpt300to470_elEta_predicted = (TH1F*) ((_file2->Get("QCDpt300to470_elEta"))->Clone("QCDpt300to470_elEta_predicted"));
  QCDpt300to470_elEta_predicted->Rebin(rebinvalue_eta);
  QCDpt300to470_elEta_predicted->SetLineColor(kBlue);
  QCDpt300to470_elEta_predicted->SetLineWidth(2.);
  QCDpt300to470_elEta_predicted->Draw("sames");
  eleeta->Update();
  TPaveStats *stats_eleeta = (TPaveStats*)(QCDpt300to470_elEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_eleeta->SetX1NDC(0.78);
  stats_eleeta->SetY1NDC(0.43);
  stats_eleeta->SetX2NDC(0.98);
  stats_eleeta->SetY2NDC(0.71);
  eleeta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  eleeta->SaveAs("ele_eta_QCDpt300to470.png");

  // plot Pt comparison
  elept->cd();
  elept->Clear();
  TH1F* QCDpt470to800_elPt_observed = (TH1F*) ((_file0->Get("QCDpt470to800_elPt"))->Clone("QCDpt30tp80_elPt_observed"));
  QCDpt470to800_elPt_observed->Rebin(rebinvalue_pt);
  QCDpt470to800_elPt_observed->SetLineColor(kRed);
  QCDpt470to800_elPt_observed->SetLineWidth(2.);
  QCDpt470to800_elPt_observed->Draw();
  TH1F* QCDpt470to800_elPt_predicted = (TH1F*) ((_file2->Get("QCDpt470to800_elPt"))->Clone("QCDpt470to800_elPt_predicted"));
  QCDpt470to800_elPt_predicted->Rebin(rebinvalue_pt);
  QCDpt470to800_elPt_predicted->SetLineColor(kBlue);
  QCDpt470to800_elPt_predicted->SetLineWidth(2.);
  QCDpt470to800_elPt_predicted->Draw("sames");
  elept->Update();
  TPaveStats *stats_elpt = (TPaveStats*)(QCDpt470to800_elPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_elpt->SetX1NDC(0.78);
  stats_elpt->SetY1NDC(0.43);
  stats_elpt->SetX2NDC(0.98);
  stats_elpt->SetY2NDC(0.71);
  elept->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  elept->SaveAs("ele_pt_QCDpt470to800.png");

  // Plot eta comparison
  eleeta->cd();
  eleeta->Clear();
  TH1F* QCDpt470to800_elEta_observed = (TH1F*) ((_file0->Get("QCDpt470to800_elEta"))->Clone("QCDpt470to800_elEta_observed"));
  QCDpt470to800_elEta_observed->Rebin(rebinvalue_eta);
  QCDpt470to800_elEta_observed->SetLineColor(kRed);
  QCDpt470to800_elEta_observed->SetLineWidth(2.);
  QCDpt470to800_elEta_observed->Draw();
  TH1F* QCDpt470to800_elEta_predicted = (TH1F*) ((_file2->Get("QCDpt470to800_elEta"))->Clone("QCDpt470to800_elEta_predicted"));
  QCDpt470to800_elEta_predicted->Rebin(rebinvalue_eta);
  QCDpt470to800_elEta_predicted->SetLineColor(kBlue);
  QCDpt470to800_elEta_predicted->SetLineWidth(2.);
  QCDpt470to800_elEta_predicted->Draw("sames");
  eleeta->Update();
  TPaveStats *stats_eleeta = (TPaveStats*)(QCDpt470to800_elEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_eleeta->SetX1NDC(0.78);
  stats_eleeta->SetY1NDC(0.43);
  stats_eleeta->SetX2NDC(0.98);
  stats_eleeta->SetY2NDC(0.71);
  eleeta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  eleeta->SaveAs("ele_eta_QCDpt470to800.png");

  // plot Pt comparison
  elept->cd();
  elept->Clear();
  TH1F* QCDpt800toInf_elPt_observed = (TH1F*) ((_file0->Get("QCDpt800toInf_elPt"))->Clone("QCDpt800tpInf_elPt_observed"));
  QCDpt800toInf_elPt_observed->Rebin(rebinvalue_pt);
  QCDpt800toInf_elPt_observed->SetLineColor(kRed);
  QCDpt800toInf_elPt_observed->SetLineWidth(2.);
  QCDpt800toInf_elPt_observed->Draw();
  TH1F* QCDpt800toInf_elPt_predicted = (TH1F*) ((_file2->Get("QCDpt800toInf_elPt"))->Clone("QCDpt800toInf_elPt_predicted"));
  QCDpt800toInf_elPt_predicted->Rebin(rebinvalue_pt);
  QCDpt800toInf_elPt_predicted->SetLineColor(kBlue);
  QCDpt800toInf_elPt_predicted->SetLineWidth(2.);
  QCDpt800toInf_elPt_predicted->Draw("sames");
  elept->Update();
  TPaveStats *stats_elpt = (TPaveStats*)(QCDpt800toInf_elPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_elpt->SetX1NDC(0.78);
  stats_elpt->SetY1NDC(0.43);
  stats_elpt->SetX2NDC(0.98);
  stats_elpt->SetY2NDC(0.71);
  elept->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  elept->SaveAs("ele_pt_QCDpt800toInf.png");

  // Plot eta comparison
  eleeta->cd();
  eleeta->Clear();
  TH1F* QCDpt800toInf_elEta_observed = (TH1F*) ((_file0->Get("QCDpt800toInf_elEta"))->Clone("QCDpt800toInf_elEta_observed"));
  QCDpt800toInf_elEta_observed->Rebin(rebinvalue_eta);
  QCDpt800toInf_elEta_observed->SetLineColor(kRed);
  QCDpt800toInf_elEta_observed->SetLineWidth(2.);
  QCDpt800toInf_elEta_observed->Draw();
  TH1F* QCDpt800toInf_elEta_predicted = (TH1F*) ((_file2->Get("QCDpt800toInf_elEta"))->Clone("QCDpt800toInf_elEta_predicted"));
  QCDpt800toInf_elEta_predicted->Rebin(rebinvalue_eta);
  QCDpt800toInf_elEta_predicted->SetLineColor(kBlue);
  QCDpt800toInf_elEta_predicted->SetLineWidth(2.);
  QCDpt800toInf_elEta_predicted->Draw("sames");
  eleeta->Update();
  TPaveStats *stats_eleeta = (TPaveStats*)(QCDpt800toInf_elEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_eleeta->SetX1NDC(0.78);
  stats_eleeta->SetY1NDC(0.43);
  stats_eleeta->SetX2NDC(0.98);
  stats_eleeta->SetY2NDC(0.71);
  eleeta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  eleeta->SaveAs("ele_eta_QCDpt800toInf.png");

  // plot Pt comparison
  elept->cd();
  elept->Clear();
  TH1F* elPt_observed = (TH1F*) ((_file0->Get("QCDpt30to80_elPt"))->Clone("elPt_observed"));
  elPt_observed->Add(((TH1F*)(_file0->Get("QCDpt80to170_elPt"))));
  elPt_observed->Add(((TH1F*)(_file0->Get("QCDpt170to300_elPt"))));
  elPt_observed->Add(((TH1F*)(_file0->Get("QCDpt300to470_elPt"))));
  elPt_observed->Add(((TH1F*)(_file0->Get("QCDpt470to800_elPt"))));
  elPt_observed->Add(((TH1F*)(_file0->Get("QCDpt800toInf_elPt"))));
  elPt_observed->Rebin(rebinvalue_pt);
  elPt_observed->SetLineColor(kRed);
  elPt_observed->SetLineWidth(2.);
  TH1F* elPt_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_elPt"))->Clone("elPt_predicted"));
  elPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt80to170_elPt"))));
  elPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt170to300_elPt"))));
  elPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt300to470_elPt"))));
  elPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt470to800_elPt"))));
  elPt_predicted->Add(((TH1F*)(_file0->Get("QCDpt800toInf_elPt"))));
  elPt_predicted->Rebin(rebinvalue_pt);
  elPt_predicted->SetLineColor(kBlue);
  elPt_predicted->SetLineWidth(2.);
  elPt_predicted->Draw();
  elPt_observed->Draw("sames");
  elept->Update();
  TPaveStats *stats_elpt = (TPaveStats*)(elPt_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_elpt->SetX1NDC(0.78);
  stats_elpt->SetY1NDC(0.43);
  stats_elpt->SetX2NDC(0.98);
  stats_elpt->SetY2NDC(0.71);
  elept->Update();
  TLatex *   lable_ref = new TLatex(0.55,0.75,"Red: observed");
  lable_ref->SetNDC();
  lable_ref->SetTextSize(0.04);
  lable_ref->SetTextColor(kRed);
  TLatex *   lable_new = new TLatex(0.55,0.7,"Blue: predicted");
  lable_new->SetNDC();
  lable_new->SetTextSize(0.04);
  lable_new->SetTextColor(kBlue);
  lable_new->Draw();
  lable_ref->Draw();
  elept->SaveAs("ele_pt.png");

  // Plot eta comparison
  eleeta->cd();
  eleeta->Clear();
  TH1F* elEta_observed = (TH1F*) ((_file0->Get("QCDpt30to80_elEta"))->Clone("elEta_observed"));
  elEta_observed->Add(((TH1F*)(_file0->Get("QCDpt80to170_elEta"))));
  elEta_observed->Add(((TH1F*)(_file0->Get("QCDpt170to300_elEta"))));
  elEta_observed->Add(((TH1F*)(_file0->Get("QCDpt300to470_elEta"))));
  elEta_observed->Add(((TH1F*)(_file0->Get("QCDpt470to800_elEta"))));
  elEta_observed->Add(((TH1F*)(_file0->Get("QCDpt800toInf_elEta"))));
  elEta_observed->Rebin(rebinvalue_eta);
  elEta_observed->SetLineColor(kRed);
  elEta_observed->SetLineWidth(2.);
  TH1F* elEta_predicted = (TH1F*) ((_file2->Get("QCDpt30to80_elEta"))->Clone("elEta_predicted"));
  elEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt80to170_elEta"))));
  elEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt170to300_elEta"))));
  elEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt300to470_elEta"))));
  elEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt470to800_elEta"))));
  elEta_predicted->Add(((TH1F*)(_file0->Get("QCDpt800toInf_elEta"))));
  elEta_predicted->Rebin(rebinvalue_eta);
  elEta_predicted->SetLineColor(kBlue);
  elEta_predicted->SetLineWidth(2.);
  elEta_predicted->Draw();
  elEta_observed->Draw("sames");
  eleeta->Update();
  TPaveStats *stats_eleeta = (TPaveStats*)(elEta_predicted->GetListOfFunctions()->FindObject("stats"));
  stats_eleeta->SetX1NDC(0.78);
  stats_eleeta->SetY1NDC(0.43);
  stats_eleeta->SetX2NDC(0.98);
  stats_eleeta->SetY2NDC(0.71);
  eleeta->Update();
  lable_new->Draw();
  lable_ref->Draw();
  eleeta->SaveAs("ele_eta.png");

}
