/********************************************************************
* LinkDef_out.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LinkDef_out.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableLinkDef_out();
extern void G__cpp_setup_inheritanceLinkDef_out();
extern void G__cpp_setup_typetableLinkDef_out();
extern void G__cpp_setup_memvarLinkDef_out();
extern void G__cpp_setup_globalLinkDef_out();
extern void G__cpp_setup_memfuncLinkDef_out();
extern void G__cpp_setup_funcLinkDef_out();
extern void G__set_cpp_environmentLinkDef_out();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LinkDef_outLN_TClass;
extern G__linked_taginfo G__LinkDef_outLN_TBuffer;
extern G__linked_taginfo G__LinkDef_outLN_TMemberInspector;
extern G__linked_taginfo G__LinkDef_outLN_TObject;
extern G__linked_taginfo G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LinkDef_outLN_TString;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__LinkDef_outLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__LinkDef_outLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__LinkDef_outLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__LinkDef_outLN_TH1;
extern G__linked_taginfo G__LinkDef_outLN_TVar;
extern G__linked_taginfo G__LinkDef_outLN_TVarcLcLMatrixElement;
extern G__linked_taginfo G__LinkDef_outLN_TVarcLcLProcess;
extern G__linked_taginfo G__LinkDef_outLN_TVarcLcLHWWPhaseSpace;
extern G__linked_taginfo G__LinkDef_outLN_cdf_event_type;
extern G__linked_taginfo G__LinkDef_outLN_mcfm_event_type;
extern G__linked_taginfo G__LinkDef_outLN_TEvtProb;
extern G__linked_taginfo G__LinkDef_outLN_TMatrixElement;

/* STUB derived class for protected member access */
