#include "Generator.hh"
#include "KinematicSolver.hh"
#include "PhaseSpace.hh"
#include "TEvtProb.hh"
#include "TMCFM.hh"
#include "TMatrixElement.hh"
#include "TUtil.hh"
#include "TVar.hh"

#ifdef __CINT__
#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

// #pragma link C++ function ScanChain(TChain*, enum Sample, double, bool);
#pragma link C++  nestedclasses;
#pragma link C++  nestedtypedefs;


#pragma link C++  function  GetRandom;
#pragma link C++  function WWL1L2Sol_MHiggsMw1;
#pragma link C++  class  TVar;
#pragma link C++  class  TEvtProb;
#pragma link C++  class  TMatrixElement;
#pragma link C++  function breitw;
#pragma link C++  function SetTGCParameter;
#pragma link C++  function GetTGCParameter;
#pragma link C++  function SumMatrixElementPDF;



#endif
//
// File generated by rootcint at Mon Jan 24 14:05:43 2011

// Do NOT change. Changes will be lost next time file is generated
//

#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "LinkDef_out.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TVar_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_TVar(void *p = 0);
   static void *newArray_TVar(Long_t size, void *p);
   static void delete_TVar(void *p);
   static void deleteArray_TVar(void *p);
   static void destruct_TVar(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TVar*)
   {
      ::TVar *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TVar >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TVar", ::TVar::Class_Version(), "./TVar.hh", 10,
                  typeid(::TVar), DefineBehavior(ptr, ptr),
                  &::TVar::Dictionary, isa_proxy, 0,
                  sizeof(::TVar) );
      instance.SetNew(&new_TVar);
      instance.SetNewArray(&newArray_TVar);
      instance.SetDelete(&delete_TVar);
      instance.SetDeleteArray(&deleteArray_TVar);
      instance.SetDestructor(&destruct_TVar);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TVar*)
   {
      return GenerateInitInstanceLocal((::TVar*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TVar*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TEvtProb_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_TEvtProb(void *p = 0);
   static void *newArray_TEvtProb(Long_t size, void *p);
   static void delete_TEvtProb(void *p);
   static void deleteArray_TEvtProb(void *p);
   static void destruct_TEvtProb(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TEvtProb*)
   {
      ::TEvtProb *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TEvtProb >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TEvtProb", ::TEvtProb::Class_Version(), "./TEvtProb.hh", 40,
                  typeid(::TEvtProb), DefineBehavior(ptr, ptr),
                  &::TEvtProb::Dictionary, isa_proxy, 0,
                  sizeof(::TEvtProb) );
      instance.SetNew(&new_TEvtProb);
      instance.SetNewArray(&newArray_TEvtProb);
      instance.SetDelete(&delete_TEvtProb);
      instance.SetDeleteArray(&deleteArray_TEvtProb);
      instance.SetDestructor(&destruct_TEvtProb);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TEvtProb*)
   {
      return GenerateInitInstanceLocal((::TEvtProb*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TEvtProb*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TMatrixElement_ShowMembers(void *obj, TMemberInspector &R__insp, char *R__parent);
   static void *new_TMatrixElement(void *p = 0);
   static void *newArray_TMatrixElement(Long_t size, void *p);
   static void delete_TMatrixElement(void *p);
   static void deleteArray_TMatrixElement(void *p);
   static void destruct_TMatrixElement(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TMatrixElement*)
   {
      ::TMatrixElement *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TMatrixElement >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TMatrixElement", ::TMatrixElement::Class_Version(), "./TMatrixElement.hh", 23,
                  typeid(::TMatrixElement), DefineBehavior(ptr, ptr),
                  &::TMatrixElement::Dictionary, isa_proxy, 0,
                  sizeof(::TMatrixElement) );
      instance.SetNew(&new_TMatrixElement);
      instance.SetNewArray(&newArray_TMatrixElement);
      instance.SetDelete(&delete_TMatrixElement);
      instance.SetDeleteArray(&deleteArray_TMatrixElement);
      instance.SetDestructor(&destruct_TMatrixElement);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TMatrixElement*)
   {
      return GenerateInitInstanceLocal((::TMatrixElement*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TMatrixElement*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TVar::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TVar::Class_Name()
{
   return "TVar";
}

//______________________________________________________________________________
const char *TVar::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TVar*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TVar::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TVar*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TVar::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TVar*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TVar::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TVar*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TEvtProb::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TEvtProb::Class_Name()
{
   return "TEvtProb";
}

//______________________________________________________________________________
const char *TEvtProb::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TEvtProb*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TEvtProb::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TEvtProb*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TEvtProb::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TEvtProb*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TEvtProb::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TEvtProb*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TMatrixElement::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TMatrixElement::Class_Name()
{
   return "TMatrixElement";
}

//______________________________________________________________________________
const char *TMatrixElement::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TMatrixElement*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TMatrixElement::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TMatrixElement*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TMatrixElement::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TMatrixElement*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TMatrixElement::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TMatrixElement*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TVar::Streamer(TBuffer &R__b)
{
   // Stream an object of class TVar.

   ::Error("TVar::Streamer", "version id <=0 in ClassDef, dummy Streamer() called"); if (R__b.IsReading()) { }
}

//______________________________________________________________________________
void TVar::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TVar.
      TClass *R__cl = ::TVar::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TVar(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TVar : new ::TVar;
   }
   static void *newArray_TVar(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::TVar[nElements] : new ::TVar[nElements];
   }
   // Wrapper around operator delete
   static void delete_TVar(void *p) {
      delete ((::TVar*)p);
   }
   static void deleteArray_TVar(void *p) {
      delete [] ((::TVar*)p);
   }
   static void destruct_TVar(void *p) {
      typedef ::TVar current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TVar

//______________________________________________________________________________
void TEvtProb::Streamer(TBuffer &R__b)
{
   // Stream an object of class TEvtProb.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void TEvtProb::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TEvtProb.
      TClass *R__cl = ::TEvtProb::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "_seed", &_seed);
      R__insp.Inspect(R__cl, R__parent, "_ncalls", &_ncalls);
      R__insp.Inspect(R__cl, R__parent, "_smearLevel", &_smearLevel);
      R__insp.Inspect(R__cl, R__parent, "_isApplyFake", &_isApplyFake);
      R__insp.Inspect(R__cl, R__parent, "_process", &_process);
      R__insp.Inspect(R__cl, R__parent, "_matrixElement", &_matrixElement);
      R__insp.Inspect(R__cl, R__parent, "_hwwPhaseSpace", &_hwwPhaseSpace);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TEvtProb(void *p) {
      return  p ? new(p) ::TEvtProb : new ::TEvtProb;
   }
   static void *newArray_TEvtProb(Long_t nElements, void *p) {
      return p ? new(p) ::TEvtProb[nElements] : new ::TEvtProb[nElements];
   }
   // Wrapper around operator delete
   static void delete_TEvtProb(void *p) {
      delete ((::TEvtProb*)p);
   }
   static void deleteArray_TEvtProb(void *p) {
      delete [] ((::TEvtProb*)p);
   }
   static void destruct_TEvtProb(void *p) {
      typedef ::TEvtProb current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TEvtProb

//______________________________________________________________________________
void TMatrixElement::Streamer(TBuffer &R__b)
{
   // Stream an object of class TMatrixElement.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void TMatrixElement::ShowMembers(TMemberInspector &R__insp, char *R__parent)
{
      // Inspect the data members of an object of class TMatrixElement.
      TClass *R__cl = ::TMatrixElement::IsA();
      Int_t R__ncp = strlen(R__parent);
      if (R__ncp || R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__parent, "_matrixElement", &_matrixElement);
      TObject::ShowMembers(R__insp, R__parent);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TMatrixElement(void *p) {
      return  p ? new(p) ::TMatrixElement : new ::TMatrixElement;
   }
   static void *newArray_TMatrixElement(Long_t nElements, void *p) {
      return p ? new(p) ::TMatrixElement[nElements] : new ::TMatrixElement[nElements];
   }
   // Wrapper around operator delete
   static void delete_TMatrixElement(void *p) {
      delete ((::TMatrixElement*)p);
   }
   static void deleteArray_TMatrixElement(void *p) {
      delete [] ((::TMatrixElement*)p);
   }
   static void destruct_TMatrixElement(void *p) {
      typedef ::TMatrixElement current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::TMatrixElement

/********************************************************
* LinkDef_out.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && (__GNUC__ > 3) && (__GNUC_MINOR__ > 1)
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableLinkDef_out();

extern "C" void G__set_cpp_environmentLinkDef_out() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__cpp_reset_tagtableLinkDef_out();
}
#include <new>
extern "C" int G__cpp_dllrevLinkDef_out() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TVar */
static int G__LinkDef_out_562_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TString* pobj;
         TString xobj = TVar::ProcessName((int) G__int(libp->para[0]));
         pobj = new TString(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TVar::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVar::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TVar::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TVar::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const TVar*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVar*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref, (char*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVar*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TVar*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVar::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TVar::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TVar::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_562_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TVar::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic default constructor
static int G__LinkDef_out_562_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TVar *p;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TVar[n];
     } else {
       p = new((void*) gvp) TVar[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TVar;
     } else {
       p = new((void*) gvp) TVar;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LinkDef_outLN_TVar));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__LinkDef_out_562_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TVar* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TVar(*(TVar*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LinkDef_outLN_TVar));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TVar G__TTVar;
static int G__LinkDef_out_562_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TVar*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TVar*) (soff+(sizeof(TVar)*i)))->~G__TTVar();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TVar*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TVar*) (soff))->~G__TTVar();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__LinkDef_out_562_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TVar* dest = (TVar*) G__getstructoffset();
   *dest = *(TVar*) libp->para[0].ref;
   const TVar& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TEvtProb */
static int G__LinkDef_out_603_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TEvtProb* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TEvtProb[n];
     } else {
       p = new((void*) gvp) TEvtProb[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TEvtProb;
     } else {
       p = new((void*) gvp) TEvtProb;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->SetSeed((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->SetNcalls((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->SetSmearLevel((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->SetApplyFake((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->SetProcess((TVar::Process) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->SetMatrixElement((TVar::MatrixElement) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->SetHWWPhaseSpace((TVar::HWWPhaseSpace) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->LOXsec((double*) G__int(libp->para[0]), (double*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->LOXsec_foam((double*) G__int(libp->para[0]), (double*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->NeutrinoIntegrate((TVar::Process) G__int(libp->para[0]), *((cdf_event_type*) G__int(libp->para[1]))
, (double*) G__int(libp->para[2]), (double*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->SetHiggsMass((double) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TEvtProb::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TEvtProb::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TEvtProb::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TEvtProb::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TEvtProb*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TEvtProb::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TEvtProb::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TEvtProb::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_603_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TEvtProb::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__LinkDef_out_603_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TEvtProb* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TEvtProb(*(TEvtProb*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TEvtProb G__TTEvtProb;
static int G__LinkDef_out_603_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TEvtProb*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TEvtProb*) (soff+(sizeof(TEvtProb)*i)))->~G__TTEvtProb();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TEvtProb*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TEvtProb*) (soff))->~G__TTEvtProb();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__LinkDef_out_603_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TEvtProb* dest = (TEvtProb*) G__getstructoffset();
   *dest = *(TEvtProb*) libp->para[0].ref;
   const TEvtProb& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TMatrixElement */
static int G__LinkDef_out_605_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TMatrixElement::inst());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMatrixElement* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMatrixElement[n];
     } else {
       p = new((void*) gvp) TMatrixElement[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TMatrixElement;
     } else {
       p = new((void*) gvp) TMatrixElement;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
  struct G__aRyp1 { double a[1][mxpart]; }* G__Ap1 = (struct G__aRyp1*) G__int(libp->para[1]);
  struct G__aRyp2 { double a[1][11]; }* G__Ap2 = (struct G__aRyp2*) G__int(libp->para[2]);
      G__letdouble(result7, 100, (double) ((TMatrixElement*) G__getstructoffset())->SumMatrixElementPDF((TVar::Process) G__int(libp->para[0]), G__Ap1->a
, G__Ap2->a, (double*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
  struct G__aRyp1 { double a[1][mxpart]; }* G__Ap1 = (struct G__aRyp1*) G__int(libp->para[1]);
  struct G__aRyp2 { double a[1][11]; }* G__Ap2 = (struct G__aRyp2*) G__int(libp->para[2]);
      G__letint(result7, 105, (long) ((TMatrixElement*) G__getstructoffset())->MCFM_MatrixElement((TVar::Process) G__int(libp->para[0]), G__Ap1->a
, G__Ap2->a));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
  struct G__aRyp1 { double a[1][mxpart]; }* G__Ap1 = (struct G__aRyp1*) G__int(libp->para[1]);
  struct G__aRyp2 { double a[1][11]; }* G__Ap2 = (struct G__aRyp2*) G__int(libp->para[2]);
      G__letint(result7, 105, (long) ((TMatrixElement*) G__getstructoffset())->MadGraph_MatrixElement((TVar::Process) G__int(libp->para[0]), G__Ap1->a
, G__Ap2->a));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMatrixElement*) G__getstructoffset())->SetMatrixElement((TVar::MatrixElement) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TMatrixElement::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMatrixElement::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TMatrixElement::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TMatrixElement::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TMatrixElement*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMatrixElement::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMatrixElement::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TMatrixElement::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out_605_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TMatrixElement::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__LinkDef_out_605_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TMatrixElement* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TMatrixElement(*(TMatrixElement*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TMatrixElement G__TTMatrixElement;
static int G__LinkDef_out_605_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TMatrixElement*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TMatrixElement*) (soff+(sizeof(TMatrixElement)*i)))->~G__TTMatrixElement();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TMatrixElement*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TMatrixElement*) (soff))->~G__TTMatrixElement();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__LinkDef_out_605_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TMatrixElement* dest = (TMatrixElement*) G__getstructoffset();
   *dest = *(TMatrixElement*) libp->para[0].ref;
   const TMatrixElement& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */
static int G__LinkDef_out__0_1663(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      breitw(
(double) G__double(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]), (double*) G__int(libp->para[5])
, (double*) G__int(libp->para[6]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out__0_1668(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) GetRandom((TH1*) G__int(libp->para[0]), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out__0_1675(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      WWL1L2Sol_MHiggsMw1(
(cdf_event_type*) G__int(libp->para[0]), (double) G__double(libp->para[1])
, (double) G__double(libp->para[2]), (double) G__double(libp->para[3])
, (double) G__double(libp->para[4]), (double) G__double(libp->para[5])
, (double) G__double(libp->para[6]), (mcfm_event_type*) G__int(libp->para[7]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out__0_1730(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
  struct G__aRyp2 { double a[1][11]; }* G__Ap2 = (struct G__aRyp2*) G__int(libp->para[2]);
      G__letdouble(result7, 100, (double) SumMatrixElementPDF((TVar::Process) G__int(libp->para[0]), (mcfm_event_type*) G__int(libp->para[1])
, G__Ap2->a, (double*) G__int(libp->para[3])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out__0_1732(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) SetTGCParameter(*((TString*) G__int(libp->para[0])), (double) G__double(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__LinkDef_out__0_1733(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) GetTGCParameter((int) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}


/*********************************************************
* Member function Stub
*********************************************************/

/* TVar */

/* TEvtProb */

/* TMatrixElement */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncLinkDef_out {
 public:
  G__Sizep2memfuncLinkDef_out(): p(&G__Sizep2memfuncLinkDef_out::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncLinkDef_out::*p)();
};

size_t G__get_sizep2memfuncLinkDef_out()
{
  G__Sizep2memfuncLinkDef_out a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceLinkDef_out() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb))) {
     TEvtProb *G__Lderived;
     G__Lderived=(TEvtProb*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb),G__get_linked_tagnum(&G__LinkDef_outLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement))) {
     TMatrixElement *G__Lderived;
     G__Lderived=(TMatrixElement*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement),G__get_linked_tagnum(&G__LinkDef_outLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableLinkDef_out() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<TSchemaHelper>",117,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__LinkDef_outLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__LinkDef_outLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__LinkDef_outLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__LinkDef_outLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TVar */
static void G__setup_memvarTVar(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TVar));
   { TVar *p; p=(TVar*)0x1000; if (p) { }
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLMatrixElement),-1,-2,1,"MCFM=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLMatrixElement),-1,-2,1,"MadGraph=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"WW=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wp_gamma=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wm_gamma=2",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wp_1jet=3",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wm_1jet=4",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"ZZ=5",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Z_2l=6",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW=7",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"WpZ_lostW=8",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"WpZ_lostZ=9",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"ZZ_4l=10",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wgamma=11",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wegamma=12",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wmugamma=13",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wtaugamma=14",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"ttbar=15",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Zee=16",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Zmumu=17",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Ztautau=18",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Data=19",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Data_runFakes=20",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wenu=21",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wmunu=22",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wtaunu=23",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"We1jet=24",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW110=26",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW120=27",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW130=28",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW140=29",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW150=30",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW160=31",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW170=32",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW180=33",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW190=34",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW200=35",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW115=36",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW125=37",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW135=38",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW145=39",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW155=40",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW165=41",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW175=42",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW185=43",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW195=44",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW210=45",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW220=46",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW230=47",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW240=48",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW250=49",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW260=50",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW270=51",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW280=52",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW290=53",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWW300=54",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"WZ=55",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HZZ=56",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Wmu1jet=57",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"WWj=58",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"HWWj=59",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-2,1,"Null=60",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLHWWPhaseSpace),-1,-2,1,"MHMW=0",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLHWWPhaseSpace),-1,-2,1,"MH=1",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLHWWPhaseSpace),-1,-2,1,"MWMW=2",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLHWWPhaseSpace),-1,-2,1,"MHYH=3",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__LinkDef_outLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TEvtProb */
static void G__setup_memvarTEvtProb(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb));
   { TEvtProb *p; p=(TEvtProb*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->_seed)-(long)(p)),105,0,0,-1,-1,-1,1,"_seed=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_ncalls)-(long)(p)),105,0,0,-1,-1,-1,1,"_ncalls=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_smearLevel)-(long)(p)),105,0,0,-1,-1,-1,1,"_smearLevel=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_isApplyFake)-(long)(p)),105,0,0,-1,-1,-1,1,"_isApplyFake=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_process)-(long)(p)),105,0,0,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLProcess),-1,-1,1,"_process=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_matrixElement)-(long)(p)),105,0,0,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLMatrixElement),-1,-1,1,"_matrixElement=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_hwwPhaseSpace)-(long)(p)),105,0,0,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLHWWPhaseSpace),-1,-1,1,"_hwwPhaseSpace=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__LinkDef_outLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TMatrixElement */
static void G__setup_memvarTMatrixElement(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement));
   { TMatrixElement *p; p=(TMatrixElement*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement),-1,-2,4,"globalObj_=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_matrixElement)-(long)(p)),105,0,0,G__get_linked_tagnum(&G__LinkDef_outLN_TVarcLcLMatrixElement),-1,-1,1,"_matrixElement=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__LinkDef_outLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarLinkDef_out() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTVar(void) {
   /* TVar */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TVar));
   G__memfunc_setup("ProcessName",1120,G__LinkDef_out_562_0_1, 117, G__get_linked_tagnum(&G__LinkDef_outLN_TString), -1, 0, 1, 3, 1, 0, "i - - 0 - temp", (char*)NULL, (void*) (TString (*)(int))(&TVar::ProcessName), 0);
   G__memfunc_setup("Class",502,G__LinkDef_out_562_0_2, 85, G__get_linked_tagnum(&G__LinkDef_outLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&TVar::Class), 0);
   G__memfunc_setup("Class_Name",982,G__LinkDef_out_562_0_3, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TVar::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__LinkDef_out_562_0_4, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&TVar::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__LinkDef_out_562_0_5, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&TVar::Dictionary), 0);
   G__memfunc_setup("IsA",253,G__LinkDef_out_562_0_6, 85, G__get_linked_tagnum(&G__LinkDef_outLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__LinkDef_out_562_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__LinkDef_out_562_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__LinkDef_out_562_0_9, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__LinkDef_out_562_0_10, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TVar::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__LinkDef_out_562_0_11, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&TVar::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__LinkDef_out_562_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TVar::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__LinkDef_out_562_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&TVar::DeclFileLine), 0);
   // automatic default constructor
   G__memfunc_setup("TVar", 381, G__LinkDef_out_562_0_14, (int) ('i'), G__get_linked_tagnum(&G__LinkDef_outLN_TVar), -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("TVar", 381, G__LinkDef_out_562_0_15, (int) ('i'), G__get_linked_tagnum(&G__LinkDef_outLN_TVar), -1, 0, 1, 1, 1, 0, "u 'TVar' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TVar", 507, G__LinkDef_out_562_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__LinkDef_out_562_0_17, (int) ('u'), G__get_linked_tagnum(&G__LinkDef_outLN_TVar), -1, 1, 1, 1, 1, 0, "u 'TVar' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTEvtProb(void) {
   /* TEvtProb */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb));
   G__memfunc_setup("TEvtProb",790,G__LinkDef_out_603_0_1, 105, G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSeed",685,G__LinkDef_out_603_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - tmp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNcalls",905,G__LinkDef_out_603_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - tmp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSmearLevel",1308,G__LinkDef_out_603_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - tmp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetApplyFake",1193,G__LinkDef_out_603_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - tmp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetProcess",1035,G__LinkDef_out_603_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i 'TVar::Process' - 0 - tmp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMatrixElement",1643,G__LinkDef_out_603_0_7, 121, -1, -1, 0, 1, 1, 1, 0, "i 'TVar::MatrixElement' - 0 - tmp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHWWPhaseSpace",1535,G__LinkDef_out_603_0_8, 121, -1, -1, 0, 1, 1, 1, 0, "i 'TVar::HWWPhaseSpace' - 0 - tmp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LOXsec",558,G__LinkDef_out_603_0_9, 121, -1, -1, 0, 2, 1, 1, 0, 
"D - - 0 - Xsec D - - 0 - Err", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("LOXsec_foam",1072,G__LinkDef_out_603_0_10, 121, -1, -1, 0, 2, 1, 1, 0, 
"D - - 0 - Xsec D - - 0 - Err", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("NeutrinoIntegrate",1783,G__LinkDef_out_603_0_11, 121, -1, -1, 0, 4, 1, 1, 0, 
"i 'TVar::Process' - 0 - proc u 'cdf_event_type' - 0 - cdf_event "
"D - - 0 - Xsec D - - 0 - XsecErr", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetHiggsMass",1202,G__LinkDef_out_603_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "d - - 0 - mass", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__LinkDef_out_603_0_13, 85, G__get_linked_tagnum(&G__LinkDef_outLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&TEvtProb::Class), 0);
   G__memfunc_setup("Class_Name",982,G__LinkDef_out_603_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TEvtProb::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__LinkDef_out_603_0_15, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&TEvtProb::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__LinkDef_out_603_0_16, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&TEvtProb::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__LinkDef_outLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__LinkDef_out_603_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__LinkDef_out_603_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TEvtProb::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__LinkDef_out_603_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&TEvtProb::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__LinkDef_out_603_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TEvtProb::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__LinkDef_out_603_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&TEvtProb::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("TEvtProb", 790, G__LinkDef_out_603_0_25, (int) ('i'), G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb), -1, 0, 1, 1, 1, 0, "u 'TEvtProb' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TEvtProb", 916, G__LinkDef_out_603_0_26, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__LinkDef_out_603_0_27, (int) ('u'), G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb), -1, 1, 1, 1, 1, 0, "u 'TEvtProb' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTMatrixElement(void) {
   /* TMatrixElement */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement));
   G__memfunc_setup("inst",446,G__LinkDef_out_605_0_1, 85, G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TMatrixElement* (*)())(&TMatrixElement::inst), 0);
   G__memfunc_setup("TMatrixElement",1427,G__LinkDef_out_605_0_2, 105, G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SumMatrixElementPDF",1870,G__LinkDef_out_605_0_3, 100, -1, -1, 0, 4, 1, 1, 0, 
"i 'TVar::Process' - 0 - process D - - 2 - p "
"D - - 2 - flavor_msq D - - 0 - flux", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MCFM_MatrixElement",1729,G__LinkDef_out_605_0_4, 105, -1, -1, 0, 3, 1, 1, 0, 
"i 'TVar::Process' - 0 - process D - - 2 - p "
"D - - 2 - flavor_msq", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("MadGraph_MatrixElement",2210,G__LinkDef_out_605_0_5, 105, -1, -1, 0, 3, 1, 1, 0, 
"i 'TVar::Process' - 0 - process D - - 2 - p "
"D - - 2 - flavor_msq", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMatrixElement",1643,G__LinkDef_out_605_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "i 'TVar::MatrixElement' - 0 - tmp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__LinkDef_out_605_0_7, 85, G__get_linked_tagnum(&G__LinkDef_outLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (TClass* (*)())(&TMatrixElement::Class), 0);
   G__memfunc_setup("Class_Name",982,G__LinkDef_out_605_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TMatrixElement::Class_Name), 0);
   G__memfunc_setup("Class_Version",1339,G__LinkDef_out_605_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (Version_t (*)())(&TMatrixElement::Class_Version), 0);
   G__memfunc_setup("Dictionary",1046,G__LinkDef_out_605_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (void (*)())(&TMatrixElement::Dictionary), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__LinkDef_outLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 2, 1, 1, 0, 
"u 'TMemberInspector' - 1 - insp C - - 0 - parent", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__LinkDef_out_605_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__LinkDef_out_605_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TMatrixElement::DeclFileName), 0);
   G__memfunc_setup("ImplFileLine",1178,G__LinkDef_out_605_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&TMatrixElement::ImplFileLine), 0);
   G__memfunc_setup("ImplFileName",1171,G__LinkDef_out_605_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) (const char* (*)())(&TMatrixElement::ImplFileName), 0);
   G__memfunc_setup("DeclFileLine",1152,G__LinkDef_out_605_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) (int (*)())(&TMatrixElement::DeclFileLine), 0);
   // automatic copy constructor
   G__memfunc_setup("TMatrixElement", 1427, G__LinkDef_out_605_0_19, (int) ('i'), G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement), -1, 0, 1, 1, 1, 0, "u 'TMatrixElement' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TMatrixElement", 1553, G__LinkDef_out_605_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__LinkDef_out_605_0_21, (int) ('u'), G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement), -1, 1, 1, 1, 1, 0, "u 'TMatrixElement' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncLinkDef_out() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalLinkDef_out() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
   G__memfunc_setup("breitw", 653, G__LinkDef_out__0_1663, 121, -1, -1, 0, 7, 1, 1, 0, 
"d - - 0 - x1 d - - 0 - mminsq "
"d - - 0 - mmaxsq d - - 0 - rmass "
"d - - 0 - rwidth D - - 0 - msq "
"D - - 0 - wt", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("GetRandom", 897, G__LinkDef_out__0_1668, 100, -1, -1, 0, 2, 1, 1, 0, 
"U 'TH1' - 0 - his d - - 0 - r1", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("WWL1L2Sol_MHiggsMw1", 1642, G__LinkDef_out__0_1675, 121, -1, -1, 0, 8, 1, 1, 0, 
"U 'cdf_event_type' - 0 - temp d - - 0 - qx "
"d - - 0 - qy d - - 0 - MHiggs "
"d - - 0 - Mw1 d - - 0 - nuX "
"d - - 0 - nuY U 'mcfm_event_type' - 0 - sol", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("SumMatrixElementPDF", 1870, G__LinkDef_out__0_1730, 100, -1, -1, 0, 4, 1, 1, 0, 
"i 'TVar::Process' - 0 - procees U 'mcfm_event_type' - 0 - mcfm_event "
"D - - 2 - flavor_msq D - - 0 - flux", (char*) NULL
, (void*) NULL, 0);
   G__memfunc_setup("SetTGCParameter", 1451, G__LinkDef_out__0_1732, 100, -1, -1, 0, 2, 1, 1, 0, 
"u 'TString' - 0 - - d - - 0 - par", (char*) NULL
, (void*) NULL, 0);
}

static void G__cpp_setup_func17() {
   G__memfunc_setup("GetTGCParameter", 1439, G__LinkDef_out__0_1733, 100, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - i", (char*) NULL
, (void*) NULL, 0);

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcLinkDef_out() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__LinkDef_outLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TString = { "TString" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__LinkDef_outLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TH1 = { "TH1" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TVar = { "TVar" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TVarcLcLMatrixElement = { "TVar::MatrixElement" , 101 , -1 };
G__linked_taginfo G__LinkDef_outLN_TVarcLcLProcess = { "TVar::Process" , 101 , -1 };
G__linked_taginfo G__LinkDef_outLN_TVarcLcLHWWPhaseSpace = { "TVar::HWWPhaseSpace" , 101 , -1 };
G__linked_taginfo G__LinkDef_outLN_cdf_event_type = { "cdf_event_type" , 115 , -1 };
G__linked_taginfo G__LinkDef_outLN_mcfm_event_type = { "mcfm_event_type" , 115 , -1 };
G__linked_taginfo G__LinkDef_outLN_TEvtProb = { "TEvtProb" , 99 , -1 };
G__linked_taginfo G__LinkDef_outLN_TMatrixElement = { "TMatrixElement" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableLinkDef_out() {
  G__LinkDef_outLN_TClass.tagnum = -1 ;
  G__LinkDef_outLN_TBuffer.tagnum = -1 ;
  G__LinkDef_outLN_TMemberInspector.tagnum = -1 ;
  G__LinkDef_outLN_TObject.tagnum = -1 ;
  G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__LinkDef_outLN_TString.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__LinkDef_outLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__LinkDef_outLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__LinkDef_outLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__LinkDef_outLN_TH1.tagnum = -1 ;
  G__LinkDef_outLN_TVar.tagnum = -1 ;
  G__LinkDef_outLN_TVarcLcLMatrixElement.tagnum = -1 ;
  G__LinkDef_outLN_TVarcLcLProcess.tagnum = -1 ;
  G__LinkDef_outLN_TVarcLcLHWWPhaseSpace.tagnum = -1 ;
  G__LinkDef_outLN_cdf_event_type.tagnum = -1 ;
  G__LinkDef_outLN_mcfm_event_type.tagnum = -1 ;
  G__LinkDef_outLN_TEvtProb.tagnum = -1 ;
  G__LinkDef_outLN_TMatrixElement.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableLinkDef_out() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TClass);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TObject);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TString);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TH1);
   G__tagtable_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TVar),sizeof(TVar),-1,0,(char*)NULL,G__setup_memvarTVar,G__setup_memfuncTVar);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TVarcLcLMatrixElement);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TVarcLcLProcess);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_TVarcLcLHWWPhaseSpace);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_cdf_event_type);
   G__get_linked_tagnum_fwd(&G__LinkDef_outLN_mcfm_event_type);
   G__tagtable_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TEvtProb),sizeof(TEvtProb),-1,29952,(char*)NULL,G__setup_memvarTEvtProb,G__setup_memfuncTEvtProb);
   G__tagtable_setup(G__get_linked_tagnum(&G__LinkDef_outLN_TMatrixElement),sizeof(TMatrixElement),-1,29952,(char*)NULL,G__setup_memvarTMatrixElement,G__setup_memfuncTMatrixElement);
}
extern "C" void G__cpp_setupLinkDef_out(void) {
  G__check_setup_version(30051515,"G__cpp_setupLinkDef_out()");
  G__set_cpp_environmentLinkDef_out();
  G__cpp_setup_tagtableLinkDef_out();

  G__cpp_setup_inheritanceLinkDef_out();

  G__cpp_setup_typetableLinkDef_out();

  G__cpp_setup_memvarLinkDef_out();

  G__cpp_setup_memfuncLinkDef_out();
  G__cpp_setup_globalLinkDef_out();
  G__cpp_setup_funcLinkDef_out();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncLinkDef_out();
  return;
}
class G__cpp_setup_initLinkDef_out {
  public:
    G__cpp_setup_initLinkDef_out() { G__add_setup_func("LinkDef_out",(G__incsetup)(&G__cpp_setupLinkDef_out)); G__call_setup_funcs(); }
   ~G__cpp_setup_initLinkDef_out() { G__remove_setup_func("LinkDef_out"); }
};
G__cpp_setup_initLinkDef_out G__cpp_setup_initializerLinkDef_out;

